# Generated by Django 4.0.2 on 2022-02-15 13:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_body_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, validators=[blog.models.validate_mail]),
        ),
    ]
